### ISSUE TITLE
Installation Fails running   print (m.group(0))

### ISSUE THREAD

**Issue by dktshudy** [KaOSx/live-uefi#17] opened 2022-10-20 10:34 UTC
.. Running ("setcap", "cap_net_raw=ep", "/usr/bin/ping") 
Python Error:
 <class 'AttributeError'> 
 'NoneType' object has no attribute 'group' 
 File "/usr/lib/calamares/modules/userkf5/main.py", line 133, in run
    print (m.group(0)) 

[installation.log](https://github.com/KaOSx/live-uefi/files/9828880/installation.log)

**Comment by demmm** [comment] 2022-10-20 10:37
This is almost certainly not a bug, but install media created in an unsupported way, see:
https://kaosx.us/docs/usb_flash/
Especially the warning at the top & bottom of that page.

**Comment by dktshudy** [comment] 2022-10-20 11:15
Could be.  I created the USB install with the latest Rufus in Windows using the ISO, which usually works for me on most distributions. I'll try again.

**Comment by dktshudy** [comment] 2022-10-20 11:17
And now I see big and bold...
"Unetbootin and Rufus are NOT compatible with KaOS."  

Why?  That seems like a bad choice.  Both are very nice tools.

**Comment by dktshudy** [comment] 2022-10-20 11:36
The documentation needs a refresh.  The link to SUSE Studio ImageWriter is invalid and I'm having difficulty finding a binary to download.  Did find https://software.opensuse.org/package/imagewriter which now says, "There is no official package available for openSUSE Leap 15.4"  They're using Etcher now, which is a horrible little piece of code.

If dd is the only option for a windows user, KAOS will surely suffer.

**Comment by dktshudy** [comment] 2022-10-20 12:15
I used Etcher and the install succeeded.  Boots to a blank screen.  My setup isn't typical, I use a 48" LG OLED TV as a monitor with an Nvidia 3080.  Usually when I have the blank screen problem, an Alt-F1 back to F6 or 7 does the trick.  Has no effect with this install.  Switching TV inputs is also a little trick I've used and also had no effect.

Overall not a great experience.  I'll go digging through the logs at some point but fed up now.  Sorry guys.

**Comment by demmm** [comment] 2022-10-20 14:46
Edger is also not supported. You can use Rufus, ONLY if you select the *dd* option.
Closing since not a bug, if you want to discuss further, use the forum:
https://forum.kaosx.us/

**Closed by demmm** 2022-10-20 14:46 UTC
Labels: invalid

**Comment by ShalokShalom** [comment] 2022-10-20 21:36
> The documentation needs a refresh. The link to SUSE Studio ImageWriter is invalid and I'm having difficulty finding a binary to download. Did find https://software.opensuse.org/package/imagewriter which now says, "There is no official package available for openSUSE Leap 15.4" They're using Etcher now, which is a horrible little piece of code.
> 
> If dd is the only option for a windows user, KAOS will surely suffer.

I told demm about the broken link to the SUSE Image writer already a couple of years ago ^^

Before that, it was somehow half broken anyway, since it could see no .iso files by default, only .img 😂

Etcher is perfectly working in my experience with KaOS.

**Comment by ShalokShalom** [comment] 2022-10-20 21:38
And I would recommend you to boot the live mode and by that, the installation with 'nvidia non-free' selected in the boot menu, this could solve your issue. :)
